"use client";

import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { useAmbient } from "@/components/ambient/ambient-provider";
import { toLinearRgb } from "@/core/ambient";
import type { AssistantState } from "@/core/types";
import type { ElmoEmotion, ElmoGaze, OrbPerformanceMetrics, OrbWebGLSettings } from "./elmo-orb-settings";
import { ELMO_STATE_LABELS } from "./elmo-state";
import styles from "./elmo-orb-webgl.module.css";

type Vec3Tuple = [number, number, number];
type PrototypeState = { colorA: Vec3Tuple; colorB: Vec3Tuple; eyeGlow: Vec3Tuple; browColor: Vec3Tuple; filament: number; wobble: number; speed: number; swirl: number; stretch: number; chaos: number; scale: number; focus: number; follow: number; gazeX: number; gazeY: number; eyeHeight: number; browLift: number; browAngle: number; browOffset: number };
type PrototypeExpression = { eyeWidth: number; eyeHeight: number; gap: number; arc: number; lid: number; angle: number; lift: number; curve: number; browLeft: number; browRight: number; gazeX: number; gazeY: number };

const BASE_STATE: PrototypeState = { colorA: [1, .78, .45], colorB: [.45, .6, 1], eyeGlow: [.3, .42, 1], browColor: [1, .93, .8], filament: .35, wobble: .03, speed: .4, swirl: .2, stretch: 0, chaos: 0, scale: 1, focus: 0, follow: 1, gazeX: 0, gazeY: 0, eyeHeight: 1, browLift: 0, browAngle: 0, browOffset: 0 };
const state = (value: Partial<PrototypeState>): PrototypeState => ({ ...BASE_STATE, ...value, colorA: value.colorA ?? [...BASE_STATE.colorA], colorB: value.colorB ?? [...BASE_STATE.colorB], eyeGlow: value.eyeGlow ?? [...BASE_STATE.eyeGlow], browColor: value.browColor ?? [...BASE_STATE.browColor] });
const STATES: Record<AssistantState, PrototypeState> = {
  IDLE: state({}),
  LISTENING: state({ colorA: [.45, .65, 1], colorB: [.3, .45, 1], filament: .3, speed: .5, swirl: .25, focus: 1, follow: .8, eyeHeight: 1.12, browLift: 9, browColor: [.85, .92, 1] }),
  THINKING: state({ colorA: [1, .55, .4], colorB: [.55, .4, 1], filament: 1, wobble: .05, speed: 1.2, swirl: 1.6, follow: .25, gazeX: .55, gazeY: -.7, eyeHeight: .95, browLift: 4, browOffset: 14, browColor: [.9, .88, 1] }),
  TOOL_EXECUTION: state({ colorA: [1, .62, .25], colorB: [.4, .5, 1], filament: .6, speed: .8, swirl: .8, stretch: 1, follow: .3, gazeX: .9, eyeHeight: .9, browAngle: .3, browColor: [1, .9, .75] }),
  SPEAKING: state({ colorA: [1, .75, .4], colorB: [.55, .55, 1], filament: .7, wobble: .04, speed: 1, swirl: .6, follow: .6, browLift: 6 }),
  ERROR: state({ colorA: [1, .15, .3], colorB: [.85, .1, .45], filament: .8, wobble: .07, speed: 3, swirl: 1, chaos: 1, scale: .93, follow: .3, browAngle: -.4, eyeGlow: [1, .35, .55], browColor: [1, .55, .65] }),
};

const BASE_EXPRESSION: PrototypeExpression = { eyeWidth: 34, eyeHeight: 50, gap: 118, arc: 0, lid: 0, angle: .05, lift: 0, curve: .25, browLeft: 0, browRight: 0, gazeX: 0, gazeY: 0 };
const expression = (value: Partial<PrototypeExpression>): PrototypeExpression => ({ ...BASE_EXPRESSION, ...value });
const EXPRESSIONS: Record<ElmoEmotion, PrototypeExpression> = {
  neutral: expression({}), happy: expression({ eyeHeight: 32, arc: 1, angle: -.12, lift: 10, curve: .62, browLeft: 6, browRight: 6 }), curious: expression({ eyeWidth: 35, eyeHeight: 40, lid: .08, angle: -.02, lift: 10, browLeft: 22, browRight: 2, curve: .32, gazeX: .38, gazeY: -.42 }), focused: expression({ eyeHeight: 34, lid: .2, angle: .14, lift: 2, curve: .18, browLeft: 6, browRight: 6, gazeX: .08, gazeY: -.08 }), surprised: expression({ eyeWidth: 28, eyeHeight: 46, gap: 122, angle: -.05, lift: 24, curve: .5 }), sleepy: expression({ eyeHeight: 32, lid: .55, angle: .1, lift: -10, curve: .1, gazeY: .3 }), excited: expression({ eyeWidth: 38, eyeHeight: 56, gap: 120, angle: -.06, lift: 22, curve: .6, browLeft: 10, browRight: 10 }), concerned: expression({ eyeWidth: 33, eyeHeight: 40, gap: 119, lid: .16, angle: -.12, lift: 14, curve: -.22, gazeY: .18, browLeft: 12, browRight: 12 }),
};
const GAZE: Record<ElmoGaze, [number, number]> = { neutral: [0, 0], user: [0, 0], content: [.55, -.04], anticipate: [.82, -.08] };

const CAMERA_BASE_DISTANCE = 3.78;
const CAMERA_STRETCH_ALLOWANCE = .34;
const CAMERA_CHAOS_ALLOWANCE = .16;
const CAMERA_VOICE_ALLOWANCE = .1;
const STRETCH_RECENTER = .14;
const ELMO_MOTION_TIME_SCALE = .68;

const NOISE = `float h(vec3 p){p=fract(p*.3183099+.1);p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));} float nz(vec3 x){vec3 i=floor(x),f=fract(x);f=f*f*(3.-2.*f);return mix(mix(mix(h(i),h(i+vec3(1,0,0)),f.x),mix(h(i+vec3(0,1,0)),h(i+vec3(1,1,0)),f.x),f.y),mix(mix(h(i+vec3(0,0,1)),h(i+vec3(1,0,1)),f.x),mix(h(i+vec3(0,1,1)),h(i+vec3(1,1,1)),f.x),f.y),f.z);}`;
const VERTEX = `uniform float uTime,uWob,uSpd,uAmp,uCh,uStr;varying vec3 vN,vV,vP;${NOISE} void main(){vec3 p=position;float t=uTime;float d=(nz(p*1.4+vec3(0.,t*uSpd,t*uSpd*.7))-.5)*uWob*2.+(nz(p*3.+t*uSpd*1.6)-.5)*uWob*.6+uAmp*.05*nz(p*2.+t*3.);d+=uCh*.12*(nz(p*5.+t*9.)-.5);vec3 q=p*(1.+d);float s=smoothstep(-.2,1.,p.x);q.x+=uStr*.55*s*s;q.yz*=1.-uStr*.28*s;vN=normalize(normalMatrix*normalize(mix(normal,normalize(q),.5)));vec4 mv=modelViewMatrix*vec4(q,1.);vV=-mv.xyz;vP=p;gl_Position=projectionMatrix*mv;}`;
const FRAGMENT = `uniform float uTime,uFil,uSw,uFoc,uGlow,uSafe,uOpaque,uBgLum,uCoreDepth,uRimStrength,uHiStrength,uShellWhite,uWarm;uniform vec3 uA,uB,uCore,uRim,uHi;varying vec3 vN,vV,vP;${NOISE} void main(){vec3 N=normalize(vN)*(gl_FrontFacing?1.:-1.);vec3 V=normalize(vV);float nv=clamp(dot(N,V),0.,1.);float fr=pow(1.-nv,2.2);float k=smoothstep(-.7,.8,N.y*.7+N.x*.5);float c=cos(uTime*uSw*.3),s=sin(uTime*uSw*.3);vec3 q=vec3(c*vP.x-s*vP.z,vP.y,s*vP.x+c*vP.z)*2.2;float r1=1.-abs(nz(q*1.6+uTime*.12)*2.-1.);float r2=1.-abs(nz(q*3.1-uTime*.17)*2.-1.);float fil=(pow(r1,16.)+.6*pow(r2,18.))*uFil*(.35+.65*fr);vec3 L=normalize(vec3(-1.18,.95,.08));float sp=pow(max(dot(N,normalize(L+V)),0.),110.);vec3 L2=normalize(vec3(1.28,-.72,.06));float sp2=pow(max(dot(N,normalize(L2+V)),0.),62.);float zone1=1.-smoothstep(0.,.34,length(vP.xy-vec2(-.55,.48)));float zone2=1.-smoothstep(0.,.31,length(vP.xy-vec2(.58,-.38)));float face=1.-smoothstep(uSafe,uSafe+.22,length(vec2(vP.x/.68,(vP.y+.02)/.58)));float front=smoothstep(.1,.72,vP.z);float clear=1.-face*front*.68;sp*=zone1*clear;sp2*=zone2*clear;fil*=1.-face*front*.28;float inner=.06+.12*(1.-nv);float sceneLight=smoothstep(.12,.72,uBgLum);float warmSide=mix(1.,1.-smoothstep(-.55,.55,N.x)*.78,uWarm);vec3 goldenRim=mix(uRim,vec3(uRim.r,min(1.,uRim.g*1.12),uRim.b*.42),uWarm);vec3 rimColor=mix(uCore,goldenRim,warmSide);vec3 internal=mix(uCore,rimColor,.24);vec3 low=uCore*(nv*.78*uCoreDepth+inner*.18)+rimColor*(fr*.36*uRimStrength+inner*.08)+internal*fil*.82+uHi*(sp*.38+sp2*.09)*uHiStrength*uShellWhite+uCore*uFoc*pow(max(N.z,0.),3.)*.16;vec3 high=uCore*(nv*.72*uCoreDepth+inner*.1)+rimColor*(fr*.24*uRimStrength+inner*.05)+internal*fil*.55+uHi*(sp*.24+sp2*.06)*uHiStrength*uShellWhite+uCore*uFoc*pow(max(N.z,0.),3.)*.13;vec3 stateTint=mix(uA,uB,k);vec3 col=mix(low,high,sceneLight)+stateTint*fil*.055+uCore*nv*uOpaque*.12;float a=max(clamp(inner*.4+fr*.23+fil*.13,0.,.6),mix(nv*.3+fr*.2,nv*.58+fr*.25,sceneLight));a*=1.+(uCoreDepth-1.)*.12;a=mix(a,max(a,.72),uOpaque);gl_FragColor=vec4(col*uGlow,a);}`;

function cloneState(value: PrototypeState): PrototypeState { return { ...value, colorA: [...value.colorA], colorB: [...value.colorB], eyeGlow: [...value.eyeGlow], browColor: [...value.browColor] }; }
function approach(target: Record<string, unknown>, source: Record<string, unknown>, amount: number) { for (const key of Object.keys(target)) { const current = target[key]; const next = source[key]; if (Array.isArray(current) && Array.isArray(next)) current.forEach((value, index) => { current[index] = value + (next[index] - value) * amount; }); else if (typeof current === "number" && typeof next === "number") target[key] = current + (next - current) * amount; } }
const rgba = (color: Vec3Tuple, alpha = 1) => `rgba(${color.map((channel) => Math.round(THREE.MathUtils.clamp(channel, 0, 1) * 255)).join(",")},${alpha})`;

function drawFace(context: CanvasRenderingContext2D, currentExpression: PrototypeExpression, currentState: PrototypeState, blink: number, gazeX: number, gazeY: number, voice: number, intensity: number) {
  context.clearRect(0, 0, 512, 512); const eyeColor: Vec3Tuple = [.68, .79, .98];
  for (const direction of [-1, 1]) { const centerX = 256 + direction * currentExpression.gap + gazeX * 10; const centerY = 281 + gazeY * 8; const radiusX = currentExpression.eyeWidth; const radiusY = Math.max(currentExpression.eyeHeight * currentState.eyeHeight * blink, 2); context.shadowBlur = 0; const glow = context.createRadialGradient(centerX, centerY, 0, centerX, centerY, radiusY * 2.4); glow.addColorStop(0, rgba(currentState.eyeGlow, .28)); glow.addColorStop(.5, rgba(currentState.eyeGlow, .12)); glow.addColorStop(1, rgba(currentState.eyeGlow, 0)); context.fillStyle = glow; context.fillRect(centerX - 100, centerY - 120, 200, 240); context.shadowColor = rgba(currentState.eyeGlow, .65); context.shadowBlur = 18; const angle = currentExpression.angle + currentState.browAngle; const positive = Math.max(angle, 0); const eyeTop = centerY - radiusY + currentExpression.lid * 2 * radiusY; const curve = radiusY * .9;
    if (currentExpression.arc < .98) { context.save(); context.globalAlpha = (1 - currentExpression.arc) * intensity; context.beginPath(); context.moveTo(centerX - radiusX * 3, eyeTop + direction * positive * curve * 3); context.lineTo(centerX + radiusX * 3, eyeTop - direction * positive * curve * 3); context.lineTo(centerX + radiusX * 3, 600); context.lineTo(centerX - radiusX * 3, 600); context.closePath(); context.clip(); context.fillStyle = rgba(eyeColor, .94); context.beginPath(); context.ellipse(centerX, centerY, radiusX, radiusY, 0, 0, Math.PI * 2); context.fill(); context.restore(); }
    if (currentExpression.arc > .02) { context.save(); context.globalAlpha = currentExpression.arc * intensity; context.strokeStyle = rgba(eyeColor); context.lineWidth = 11; context.lineCap = "round"; context.beginPath(); context.arc(centerX, centerY + 16, radiusX * 1.3, Math.PI * 1.1, Math.PI * 1.9); context.stroke(); context.restore(); }
    const length = 60; const browY = centerY - 88 - currentExpression.lift - currentState.browLift - (direction < 0 ? currentExpression.browLeft + currentState.browOffset : currentExpression.browRight) - gazeY * 4 - voice * (direction > 0 ? 12 : 7); context.globalAlpha = intensity; context.shadowColor = rgba(currentState.browColor, .78); context.shadowBlur = 14; context.strokeStyle = rgba(currentState.browColor); context.lineWidth = 15; context.lineCap = "round"; context.beginPath(); context.moveTo(centerX + direction * length, browY - angle * length * .55); context.quadraticCurveTo(centerX, browY - currentExpression.curve * 60, centerX - direction * length, browY + angle * length * .55); context.stroke(); }
  context.globalAlpha = 1;
}

const EMOTION_LABELS: Record<ElmoEmotion, string> = { neutral: "neutra", happy: "feliz", curious: "curiosa", focused: "concentrada", surprised: "surpresa", sleepy: "sonolenta", excited: "empolgada", concerned: "preocupada" };
type Props = { state: AssistantState; emotion: ElmoEmotion; gaze: ElmoGaze; blinkEnabled: boolean; settings: OrbWebGLSettings; reducedMotion: boolean; reducedTransparency: boolean; hasContext: boolean; onMetrics: (metrics: OrbPerformanceMetrics) => void; onFallback: (reason: string) => void; initStartedAt: number };

export function ElmoOrbWebGL({ state: assistantState, emotion, gaze, blinkEnabled, settings, reducedMotion, reducedTransparency, hasContext, onMetrics, onFallback, initStartedAt }: Props) {
  const ambient = useAmbient(); const canvasRef = useRef<HTMLCanvasElement>(null); const hostRef = useRef<HTMLDivElement>(null); const ambientRender = useMemo(() => ({ core: toLinearRgb(ambient.tokens.elmoCore), rim: toLinearRgb(ambient.tokens.elmoRim), highlight: toLinearRgb(ambient.tokens.elmoHighlight), backgroundLuminance: ambient.tokens.estimatedBackgroundLuminance, coreDepth: ambient.tokens.orbCoreDepth, rimIntensity: ambient.tokens.orbRimIntensity, highlightIntensity: ambient.tokens.orbHighlightIntensity, shellWhitening: ambient.tokens.orbShellWhitening, warmLight: ambient.tokens.orbWarmLight }), [ambient.tokens]); const latest = useRef({ assistantState, emotion, gaze, blinkEnabled, settings, reducedMotion, reducedTransparency, ambientRender, onMetrics, onFallback });
  useEffect(() => { latest.current = { assistantState, emotion, gaze, blinkEnabled, settings, reducedMotion, reducedTransparency, ambientRender, onMetrics, onFallback }; }, [ambientRender, assistantState, blinkEnabled, emotion, gaze, onFallback, onMetrics, reducedMotion, reducedTransparency, settings]);
  useEffect(() => {
    const canvas = canvasRef.current; const host = hostRef.current; if (!canvas || !host) return; let renderer: THREE.WebGLRenderer;
    try { renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true, powerPreference: "high-performance" }); } catch { latest.current.onFallback("WebGL indisponível neste dispositivo"); return; }
    const initializationMs = Math.round(performance.now() - initStartedAt); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5)); renderer.setClearColor(0x000000, 0); const scene = new THREE.Scene(); const camera = new THREE.PerspectiveCamera(40, 1, .1, 50); camera.position.set(0, .15, CAMERA_BASE_DISTANCE); camera.lookAt(0, 0, 0);
    const uniforms = { uTime: { value: 0 }, uWob: { value: .03 }, uSpd: { value: .4 }, uAmp: { value: 0 }, uCh: { value: 0 }, uStr: { value: 0 }, uA: { value: new THREE.Vector3() }, uB: { value: new THREE.Vector3() }, uCore: { value: new THREE.Vector3() }, uRim: { value: new THREE.Vector3() }, uHi: { value: new THREE.Vector3() }, uFil: { value: .35 }, uSw: { value: .2 }, uFoc: { value: 0 }, uGlow: { value: 1 }, uSafe: { value: .74 }, uOpaque: { value: 0 }, uBgLum: { value: .5 }, uCoreDepth: { value: 1 }, uRimStrength: { value: 1 }, uHiStrength: { value: 1 }, uShellWhite: { value: 1 }, uWarm: { value: 0 } };
    const shellMaterial = new THREE.ShaderMaterial({ uniforms, vertexShader: VERTEX, fragmentShader: FRAGMENT, transparent: true, depthWrite: false, side: THREE.DoubleSide, blending: THREE.CustomBlending, blendSrc: THREE.OneFactor, blendDst: THREE.OneMinusSrcAlphaFactor }); const shellGeometry = new THREE.SphereGeometry(1, 96, 96); const shell = new THREE.Mesh(shellGeometry, shellMaterial); shell.frustumCulled = false; shell.renderOrder = 1; const orb = new THREE.Group(); orb.add(shell); scene.add(orb);
    const faceCanvas = document.createElement("canvas"); faceCanvas.width = faceCanvas.height = 512; const faceContext = faceCanvas.getContext("2d"); if (!faceContext) { latest.current.onFallback("Canvas facial indisponível"); renderer.dispose(); return; } const faceTexture = new THREE.CanvasTexture(faceCanvas); const faceMaterial = new THREE.MeshBasicMaterial({ map: faceTexture, transparent: true, blending: THREE.AdditiveBlending, depthWrite: false }); const faceGeometry = new THREE.SphereGeometry(.93, 48, 48, Math.PI / 2 - .85, 1.7, Math.PI / 2 - .85, 1.7); const face = new THREE.Mesh(faceGeometry, faceMaterial); face.renderOrder = 2; orb.add(face);
    const currentState = cloneState(STATES.IDLE); const currentExpression = { ...EXPRESSIONS.neutral }; const pointer: [number, number] = [0, 0]; const smoothGaze: [number, number] = [0, 0]; let then = performance.now(); let elapsed = 0; let nextBlink = 3 + Math.random() * 3; let blinkStarted = -9; let voice = 0; let cameraDistance = CAMERA_BASE_DISTANCE; let frames = 0; let sampleTime = 0; let frameId = 0; let active = true;
    const pointerMove = (event: PointerEvent) => { const bounds = canvas.getBoundingClientRect(); pointer[0] = THREE.MathUtils.clamp(((event.clientX - bounds.left) / bounds.width - .5) * 2, -1, 1); pointer[1] = THREE.MathUtils.clamp(((event.clientY - bounds.top) / bounds.height - .5) * 2, -1, 1); }; canvas.addEventListener("pointermove", pointerMove); const lost = (event: Event) => { event.preventDefault(); latest.current.onFallback("Contexto WebGL perdido"); }; canvas.addEventListener("webglcontextlost", lost);
    const resize = () => { const width = host.clientWidth; const height = host.clientHeight; renderer.setSize(width, height, false); camera.aspect = width / Math.max(1, height); camera.updateProjectionMatrix(); }; const observer = new ResizeObserver(resize); observer.observe(host); resize();
    const render = (now: number) => { if (!active) return; frameId = requestAnimationFrame(render); const delta = Math.min((now - then) / 1000, .05); then = now; const props = latest.current; const motion = props.reducedMotion ? .12 : 1; elapsed += delta * motion; const motionTime = elapsed * ELMO_MOTION_TIME_SCALE; approach(currentState as unknown as Record<string, unknown>, STATES[props.assistantState] as unknown as Record<string, unknown>, 1 - Math.exp(-delta * 3.5)); approach(currentExpression as unknown as Record<string, unknown>, EXPRESSIONS[props.emotion] as unknown as Record<string, unknown>, 1 - Math.exp(-delta * 7));
      const targetVoice = props.assistantState === "SPEAKING" ? Math.max(0, .55 + .45 * Math.sin(motionTime * 8.1) * Math.sin(motionTime * 2.3 + 1) + .25 * Math.sin(motionTime * 13)) : 0; voice += (targetVoice - voice) * (1 - Math.exp(-delta * 14)); if (props.blinkEnabled && !props.reducedMotion && elapsed > nextBlink) { blinkStarted = elapsed; nextBlink = elapsed + 3 + Math.random() * 4; } const duration = props.emotion === "sleepy" ? .24 : .18; const phase = (elapsed - blinkStarted) / duration; const blink = phase >= 0 && phase < 1 ? 1 - Math.sin(Math.PI * phase) * .92 : 1;
      const target = GAZE[props.gaze]; const follow = props.settings.followCursor ? currentState.follow : 0; const gain = 1 - Math.exp(-delta * 6); smoothGaze[0] += (pointer[0] * follow + target[0] + currentState.gazeX + currentExpression.gazeX - smoothGaze[0]) * gain; smoothGaze[1] += (-pointer[1] * follow + target[1] + currentState.gazeY + currentExpression.gazeY - smoothGaze[1]) * gain; const gazeX = THREE.MathUtils.clamp(smoothGaze[0] + Math.sin(motionTime * .9) * .06 + currentState.chaos * Math.sin(motionTime * 50) * .08, -1.2, 1.2); const gazeY = THREE.MathUtils.clamp(smoothGaze[1] + Math.sin(motionTime * 1.3 + 2) * .05, -1.2, 1.2); drawFace(faceContext, currentExpression, currentState, blink, gazeX, gazeY, voice, props.settings.faceIntensity); faceTexture.needsUpdate = true;
      const bob = Math.sin(motionTime * 1.1) * .06; const scale = currentState.scale * (1 + Math.sin(motionTime * 1.6) * .015) * (1 + voice * .05); const targetState = STATES[props.assistantState]; const stretchDemand = Math.max(currentState.stretch, targetState.stretch); const chaosDemand = Math.max(currentState.chaos, targetState.chaos); const safeCameraDistance = CAMERA_BASE_DISTANCE + stretchDemand * CAMERA_STRETCH_ALLOWANCE + chaosDemand * CAMERA_CHAOS_ALLOWANCE + voice * CAMERA_VOICE_ALLOWANCE; cameraDistance = THREE.MathUtils.damp(cameraDistance, safeCameraDistance, safeCameraDistance > cameraDistance ? 12 : 5, delta); camera.position.z = cameraDistance; camera.lookAt(0, 0, 0); orb.position.set(-currentState.stretch * STRETCH_RECENTER + currentState.chaos * Math.sin(motionTime * 37) * Math.sin(motionTime * 23) * .03, bob, 0); orb.scale.set(scale * (1 + voice * .025), scale * (1 - voice * .018), scale * (1 + voice * .025)); const lean = currentState.focus + .3; orb.rotation.set(Math.sin(motionTime * .45) * .04 + smoothGaze[1] * .12 * lean, Math.sin(motionTime * .6) * .1 + smoothGaze[0] * .18 * lean, Math.sin(motionTime * .5) * .02); face.rotation.set(gazeY * .2, gazeX * .3, 0); face.position.x = currentState.stretch * .2;
      const color = props.ambientRender; uniforms.uTime.value = motionTime; uniforms.uWob.value = currentState.wobble * (.72 + props.settings.distortion * 2.8); uniforms.uSpd.value = currentState.speed * (.7 + props.settings.temporalDistortion * 5); uniforms.uAmp.value = voice; uniforms.uCh.value = currentState.chaos; uniforms.uStr.value = currentState.stretch; uniforms.uA.value.set(...currentState.colorA); uniforms.uB.value.set(...currentState.colorB); uniforms.uCore.value.set(...color.core); uniforms.uRim.value.set(...color.rim); uniforms.uHi.value.set(...color.highlight); uniforms.uFil.value = currentState.filament * (.8 + props.settings.internalMatterIntensity * .6); uniforms.uSw.value = currentState.swirl * (.65 + props.settings.innerMovementSpeed * 2); uniforms.uFoc.value = currentState.focus; uniforms.uGlow.value = 1 + props.settings.environmentIntensity * .16; uniforms.uSafe.value = props.settings.faceSafeZone; uniforms.uOpaque.value = props.reducedTransparency ? 1 : 0; uniforms.uBgLum.value = color.backgroundLuminance; uniforms.uCoreDepth.value = color.coreDepth; uniforms.uRimStrength.value = color.rimIntensity; uniforms.uHiStrength.value = color.highlightIntensity; uniforms.uShellWhite.value = color.shellWhitening; uniforms.uWarm.value = color.warmLight; renderer.render(scene, camera); frames += 1; sampleTime += delta; if (sampleTime >= 1) { const fps = frames / sampleTime; props.onMetrics({ fps: Math.round(fps), frameTimeMs: Number((1000 / Math.max(1, fps)).toFixed(1)), sampleLimited: fps < 10, drawCalls: renderer.info.render.calls, triangles: renderer.info.render.triangles, geometries: renderer.info.memory.geometries, textures: renderer.info.memory.textures, dpr: Number(renderer.getPixelRatio().toFixed(2)), initTimeMs: initializationMs }); frames = 0; sampleTime = 0; } };
    frameId = requestAnimationFrame(render); return () => { active = false; cancelAnimationFrame(frameId); observer.disconnect(); canvas.removeEventListener("pointermove", pointerMove); canvas.removeEventListener("webglcontextlost", lost); shellGeometry.dispose(); shellMaterial.dispose(); faceGeometry.dispose(); faceMaterial.dispose(); faceTexture.dispose(); renderer.dispose(); };
  }, [initStartedAt]);
  const label = ELMO_STATE_LABELS[assistantState]; return <figure className={styles.figure} data-state={assistantState} data-has-context={hasContext} data-follow-cursor={settings.followCursor} role="img" aria-label={`Elmo WebGL: ${label}, expressão ${EMOTION_LABELS[emotion]}`}><div ref={hostRef} className={styles.canvasWrap} aria-hidden="true"><canvas ref={canvasRef} /></div><figcaption className={styles.caption} aria-live="polite"><span className={styles.stateMark} aria-hidden="true" />{label}</figcaption></figure>;
}
